### ISSUE TITLE
RunTime Exception

### ISSUE THREAD

**Issue by kun-hadi** [roomorama/Caldroid#332] opened 2015-10-06 21:11 UTC
Dear Team

after updating android studio APIs i got this exception
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:  Caused by: java.lang.RuntimeException: Binary XML file line #13: You must supply a layout_width attribute.
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:6056)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6225)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.widget.RelativeLayout$LayoutParams.<init>(RelativeLayout.java:1246)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:1083)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.widget.RelativeLayout.generateLayoutParams(RelativeLayout.java:84)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:768)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at com.roomorama.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:1241)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:5382)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2266)
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.app.ActivityThread.access$700(ActivityThread.java:159) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:176) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5419) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862) 
10-07 00:08:57.194 4168-4168/vc.baakline E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

i read about this exception missing attributes for views in this case layout_width and layout_height is missing
Thank you in advance

**Comment by kun-hadi** [comment] 2015-10-08 21:17
any body is here

**Comment by thomasdao** [comment] 2015-10-14 02:50
Did you try compiling your app with targetSdkVersion >= 23? I believe that will fix this problem

**Comment by EmpiezaAProgramar** [comment] 2015-10-14 09:33
I am having this bug too. This bug only appears in Android 4, there are no problems with Android 5.

**Comment by EmpiezaAProgramar** [comment] 2015-10-14 10:08
I am using version 1.1.8 and everythings is ok, my app is working with Android 4. I have not use targetSdkVersion 23 because I can not change to this API or my app crash (there are many changes to do)

**Comment by KKKoTTT** [comment] 2015-11-16 16:35
The same problem. Didn't have this bug with Caldroid 2.1.0. 
Android 4.x users started to complain after updating to 2.2.1. Unfortunately i can't reproduce this bug on my devices, but as far as i understood - it isn't fixed by now, am i right?
Compiling the app with targetSdkVersion >= 23 is problematic as it requires handling runtime permissions, that is difficult to do when having legacy code.

**Comment by schopy** [comment] 2015-11-17 14:42
targetSdkVersion >= 23 doesn't solve the issue

**Comment by thomasdao** [comment] 2015-11-18 02:22
@KKKoTTT that's a valid concern, I have recompiled Caldroid with targetSdkVersion 22 and push to Maven, you can try with version 2.3.1. Let me know if it works. Btw if anyone can reproduce the bug would be great

**Comment by azizimusa** [comment] 2015-11-18 16:06
Same error.

I add 
````
<style name="CaldroidDefaultLeftButton">
        <item name="android:background">@drawable/ic_action_previous_item</item>
    </style>

    <style name="CaldroidDefaultRightButton.">
        <item name="android:background">@drawable/ic_action_next_item</item>
    </style>
````
into my caldroid theme, then this error occur

````
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime: FATAL EXCEPTION: main
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime: Process: com.skool, PID: 21685
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime: java.lang.RuntimeException: Binary XML file line #14: You must supply a layout_width attribute.
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.content.res.TypedArray.getLayoutDimension(TypedArray.java:492)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.view.ViewGroup$LayoutParams.setBaseAttributes(ViewGroup.java:5948)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:6117)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.widget.LinearLayout$LayoutParams.<init>(LinearLayout.java:1831)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:1743)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.widget.LinearLayout.generateLayoutParams(LinearLayout.java:58)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:757)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at com.roomorama.caldroid.CaldroidFragment.onCreateView(CaldroidFragment.java:1244)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.Fragment.performStart(Fragment.java:1983)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1102)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4998)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:777)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:593)
11-19 00:03:37.144 21685-21685/com.skool E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
````

**Comment by thomasdao** [comment] 2015-11-19 02:52
@azizimusa can you reproduce it with CaldroidSampleApp if it crashes? Thanks

**Comment by thomasdao** [comment] 2015-11-30 01:50
This issue should be fixed with latest Caldroid, feel free to open if you have this bug again

**Closed by thomasdao** 2015-11-30 01:50 UTC

**Comment by Ke4nuReeves** [comment] 2017-03-08 09:04
Hi, i catch  this issue with latest Caldroid on android 4.4.4
