### ISSUE TITLE
Themable caldriod?

### ISSUE THREAD

**Issue by crocodile2u** [roomorama/Caldroid#244] opened 2015-03-26 12:10 UTC
Hello. At the moment, as I see it, caldroid colors are referenced in the XML layouts as android:background="@color/color_name" This makes it difficult to apply custom themes. What if you referenced colors like this: android:background="?colorName". colorName attribute would be available in attrs.xml, and in caldroid default theme there would be an entry:
<item name="colorName">@color/color_name</item>

This way, user will be able to call caldroidFragment.setStyle() in order to change calendar appearance to their own. Drawables used for buttons etc could also be made customizable that way.

**Comment by thomasdao** [comment] 2015-03-27 04:36
@crocodile2u this is very good suggestion. I may do it when I have some time, but if you can send me a PR, will be happy to merge it

**Comment by crocodile2u** [comment] 2015-03-27 07:58
Cool, will do that in the upcoming days. Anyway I was going to make this for my project. Thanks for a great widget, btw!

**Comment by crocodile2u** [comment] 2015-03-30 11:54
I am now in the process of finalizing changes. I have come upon a n interesting decision about customizing styles of various cell states, that is, literally, use states: http://charlesharley.com/2012/programming/custom-drawable-states-in-android/

I already tried this and it worked, and the code in CaldroidGridAdapter.customizeTextView() became easy as ABC (and, it allows for customsing any combination of states, like setting custom background for today's date which is both selected and disabled).

That said, I managed to fully customize Caldroid cell views using XML styles/drawables. Styling the prev/next month buttons was also pretty easy.

However, in order to support BC, I will have to keep the existing code where various backgrounds and colors are hardcoded. I think I will make two customization modes for CaldroidFragment - LEGACY and THEMEABLE. LEGACY will be selected by default, and it won't change cell visualization for users who already rely on the existing behaviour. Switching to THEMEABLE mode will let you specify your own styles and drawables for virtually any element in Caldroid.

Right now, I am dealing with those BC issues and preparing Light and Dark default themes, so that it will be easy to switch between light and dark backgrounds. One will also be possible to extend one of the default themes which probably would suit 90% of users and only override those elements that they need.

I'll publish my changes soon and will issue a PR, keep fingers crossed ;-)

**Comment by thomasdao** [comment] 2015-03-31 01:57
The link is interesting, I don't know we can define custom state in android. I think it would be simpler to make Caldroid theme-able by default, and if some breaking change required then I would upgrade to version 2.0

**Comment by crocodile2u** [comment] 2015-03-31 08:56
@thomasdao please take a look here: https://github.com/crocodile2u/Caldroid/tree/themeable.

**Comment by crocodile2u** [comment] 2015-03-31 14:09
A sample screenshot: https://cloud.mail.ru/public/51ec53f2980d/2015-03-31%2013.59.59.png - I extended default dark theme and the result is already amazing compared with what you would get with current version of caldroid. And I even did not override arrows and apply shadows to numbers in cells ;-)

**Comment by thomasdao** [comment] 2015-04-01 04:43
This is really nice, great job :+1: . Just give me some time to review the code before merging

**Comment by thomasdao** [comment] 2015-04-01 09:45
@crocodile2u I have read through the code, it's simple enough to understand :+1: .

A few comments:

- When I swipe to different months, the blue and green cells appear again because of cell reused. This is because when we call `setCustomResources`, we set background and text resource directly instead of adding a custom state. Probably need to reset the whole cell to default appearance after `cellView.resetCustomState();`

- For default caldroid theme, `cell_bg.xml`, background for date prev/next month is white, not gray:

`<item android:drawable="@color/caldroid_white" android:state_pressed="false" caldroid:state_date_prev_next_month="true"/>`

- For `cell_text_color.xml`, should add:
`<item android:color="@color/caldroid_darker_gray" caldroid:state_date_prev_next_month="true"/>`

You should remove "LEGACY" mode as well, it makes the code more complex with no added value. The new approach is much simpler to understand and change.

Other than that, great job :clap: . Please send me a PR so I can merge, thanks

**Comment by crocodile2u** [comment] 2015-04-01 10:20
Sure, will fix those issues today and send a PR. Thanks!

**Comment by crocodile2u** [comment] 2015-04-03 10:12
@thomasdao , I've updated the repo. But I was unable to reproduce the issue with blue and green cells.

**Comment by crocodile2u** [comment] 2015-04-03 11:07
And, as you've probably already seen, I sent a PR. Cheers.

**Comment by crocodile2u** [comment] 2015-04-07 13:17
@thomasdao , any updates? Have you seen the PR?

**Comment by thomasdao** [comment] 2015-04-08 08:41
Sorry I'm away from work for last few days, will merge when I'm back, thanks

**Comment by crocodile2u** [comment] 2015-04-08 09:29
Oh, I see)) Have a nice time!

**Comment by thomasdao** [comment] 2015-04-14 03:06
@crocodile2u you can reproduce the issue with blue and green cell appearing again if you swipe several months to the right. I fixed that issue by obtaining default background and text resource from theme, and reset cellView with these default resources in `customizeTextView` method. 

I already merged your PR and will update documentation and release to Maven Central soon.

Thanks for the PR :-)

**Closed by thomasdao** 2015-04-14 03:06 UTC
